# Generated by Django 2.2.16 on 2022-10-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221017_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'подписку', 'verbose_name_plural': 'Подписки на портале'},
        ),
    ]
