# Generated by Django 2.2.16 on 2022-10-19 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20221018_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-id',), 'verbose_name': 'комментарий', 'verbose_name_plural': 'Комментарии постов'},
        ),
    ]
